spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_platform?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


server:
  port: 8081

